import { envSchema } from './schema'
import fs from 'fs'
import path from 'path'
import chalk from 'chalk'
import { ZodObject, ZodRawShape, ZodOptional, ZodDefault, ZodTypeAny } from 'zod'

function unwrapType(type: ZodTypeAny) : ZodTypeAny {
    if(type instanceof ZodOptional || type instanceof ZodDefault) {
        return unwrapType(type._def.innerType);
    }

    return type;
}

export function generateEnvExample() {
    const shape = (envSchema as ZodObject<ZodRawShape>).shape;
    let content = "# Auto-generated by env-check-ts\n\n";

    for(const key in shape) {
        const field = shape[key];
        const inner = unwrapType(field);
        const isOptional = field.isOptional() || field instanceof ZodDefault;
        const defaultValue = (field as ZodDefault<any>)._def?.defaultValue;

        const comment = isOptional ? "# optional" : "# required";
        const defaultText = typeof defaultValue === "function" ? defaultValue() : defaultValue;
        const exampleValue = defaultText ?? "";

        content += `${comment}\n${key}=${exampleValue}\n\n`;
    }

    const outputPath = path.resolve(process.cwd(), ".env.example");
    fs.writeFileSync(outputPath, content.trim() + "\n");
    console.log(chalk.green("✅ .env.example generated at: ") + outputPath);
}